OngCrud/Models/Curso.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public int CursoId { get; set; }
        public string NomeCurso { get; set; }
        public string Professor { get; set; }
        public string Status { get; set; }
    }
}

OngCrud/Models/DBModels.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OngCrud.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModel : DbContext
    {
        public DBModel()
            : base("name=DBModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Funcionario> Funcionarios { get; set; }
        public virtual DbSet<Curso> Cursos { get; set; }
    }
}

OngCrud/Models/DBModels.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Vinícius Oliveira\source\repos\OngCrud\Aps-Ong-Crud\OngCrud\Models\DBModels.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

OngCrud/Models/DBModels.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

OngCrud/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OngCrud.Models;

namespace OngCrud.Controllers
{
    public class AlunoController : Controller
    {
        // GET: Aluno
        public ActionResult Curso()
        {
            return View();
        }
        
        
        public ActionResult CursoDados()
        {
            // Retorna os dados da tabela Cursos, a partir do model criado pelo Entity Framework
            using (DBModel db = new DBModel())
            {
                List<Curso> funcList = db.Cursos.ToList<Curso>();
                return Json(new { data = funcList }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Grade()
        {
            return View();
        }

        public ActionResult Nota()
        {
            return View();
        }

        public ActionResult Tarefa()
        {
            return View();
        }
    }
}

OngCrud/Controllers/FuncionarioController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OngCrud.Models;

namespace OngCrud.Controllers
{
    public class FuncionarioController : Controller
    {
        // GET: Funcionario
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData() 
        {
            /* Método que retorna os dados em tela pra gente, utiliza o model criado pelo Entity Framework,
              assim convertemos os dados do model em um objeto do tipo lista, e retornamos em formato de Json*/
            using (DBModel db = new DBModel())
            {
                List<Funcionario> funcList = db.Funcionarios.ToList<Funcionario>();
                return Json(new { data = funcList }, JsonRequestBehavior.AllowGet);
            }
        }
        
        [HttpGet]
        public ActionResult AddOrEdit(int id = 0)
        {
            
            if (id==0)
            return View(new Funcionario());
            else
            {
                using (DBModel db = new DBModel())
                {
                    return View(db.Funcionarios.Where(x => x.FuncID==id).FirstOrDefault<Funcionario>());
                }
            }
        }

        [HttpPost]
        public ActionResult AddOrEdit(Funcionario fnc)
        {
            /* Método que permite que adicionemos ou editemos dados */
            using (DBModel db = new DBModel())
            {
                if(fnc.FuncID == 0)
                { 
                db.Funcionarios.Add(fnc);
                db.SaveChanges();
                return Json(new { success = true, message = "Salvo com sucesso!" }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    db.Entry(fnc).State = EntityState.Modified;
                    db.SaveChanges();
                    return Json(new { success = true, message = "Atualizado com sucesso!" }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            using(DBModel db = new DBModel())
            {
                Funcionario fnc = db.Funcionarios.Where(x => x.FuncID == id).FirstOrDefault<Funcionario>();
                db.Funcionarios.Remove(fnc);
                db.SaveChanges();
                return Json(new { success = true, message = "Deletado com sucesso" }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

OngCrud/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OngCrud.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Inicio() // View Inicial
        {
            return View();
        }
    }
}

OngCrud/Controllers/ProfessorController.cs
using OngCrud.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OngCrud.Controllers
{
    public class ProfessorController : Controller
    {
        // GET: Professor
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Agenda()
        {
            return View();
        }
    }
}

OngCrud/Views/Aluno/Curso.cshtml
<h2>Cursos</h2>
<table id="FuncTable" class="ui celled table" style="width:100%">
    <thead>
        <tr>
            <th>Nome do Curso</th>
            <th>Professor</th>
            <th>Status</th>
            <th></th>
        </tr>
    </thead>
</table>
<a class="btn btn-default" style="align-items:center" href="@Url.Action("Inicio", "Home")"><i class="fas fa-arrow-left"></i> Voltar</a>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.semanticui.min.css" rel="stylesheet" />


@section scripts{
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.semanticui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
    <script>
        var Popup, dataTable;
        $(document).ready(function () { // Função ajax pra popular a tabela quando a página abrir
            dataTable = $("#FuncTable").DataTable({
                "ajax": {
                    "url": "/Aluno/CursoDados",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "NomeCurso" },
                    { "data": "Professor" },
                    { "data": "Status" },
                    {
                        "data": "CursoId",
                        "visible": false,
                        "orderable": false,
                        "searchable": false,
                        "width": "165px"
                    }
                ],
                "language": {
                    "emptyTable": "Não há dados disponíveis."
                }
            });
        });
    </script>
}

OngCrud/Views/Funcionario/AddOrEdit.cshtml
@model OngCrud.Models.Funcionario
@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "Funcionario", FormMethod.Post, new { onsubmit = "return SubmitForm(this)"}))
{
    @Html.HiddenFor(model => model.FuncID)
    <div class="form-group">
        @Html.LabelFor(model => model.Nome, new { @class = "control-label" })
        @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Nome)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Cargo, new { @class = "control-label" })
        @Html.EditorFor(model => model.Cargo, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.Cargo)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Sede, new { @class = "control-label" })
        @Html.EditorFor(model => model.Sede, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Idade, new { @class = "control-label" })
        @Html.EditorFor(model => model.Idade, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Salario, new { @class = "control-label" })
        <div class="input-group">
            <span class="input-group-addon">R$</span>
            @Html.EditorFor(model => model.Salario, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>


    <div class="form-group">
        <input type="submit" value="Adicionar" class="btn btn-primary" />
        <input type="reset" value="Cancelar" class="btn" />
    </div>
}

OngCrud/Views/Funcionario/Index.cshtml
@{
    ViewBag.Title = "Cadastro de Funcionário";
}

<h2>Cadastro de funcionário</h2>

<a class="btn btn-success" style="margin-bottom:10px" onclick="PopUpForm('@Url.Action("AddOrEdit", "Funcionario")')"><i class="fas fa-plus"></i> Add New</a>
<table id="FuncTable" class="table table-striped table-bordered" style="width:100%">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Cargo</th>
            <th>Sede</th>
            <th>Idade</th>
            <th>Salario</th>
            <th></th>
        </tr>
    </thead>
</table>
<a class="btn btn-default" style="align-items:center" href="@Url.Action("Inicio", "Home")"><i class="fas fa-arrow-left"></i> Voltar</a>

<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />


@section scripts{
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
    <script>
        var Popup, dataTable;
        $(document).ready(function () { // Função ajax pra popular a tabela quando a página abrir
            dataTable = $("#FuncTable").DataTable({
                "ajax": {
                    "url": "/Funcionario/GetData",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "Nome" },
                    { "data": "Cargo" },
                    { "data": "Sede" },
                    { "data": "Idade" },
                    { "data": "Salario" },
                    {"data":"FuncID" , "render" : function (data) {
                        return "<a class='btn btn-default btn-sm' onclick=PopUpForm('@Url.Action("AddOrEdit","Funcionario")/" + data + "')><i class='fas fa-edit'></i> Edit</a><a class='btn btn-danger btn-sm' style='margin-left:5px' onclick=Delete("+data+")><i class='fas fa-trash'></i> Delete</a>";
                    },
                        "orderable": false,
                        "searchable":false,
                        "width":"165px"
                    }
                ],
                "language": {
                    "emptyTable": "Não há dados disponíveis."
                }
            });
        });
        function PopUpForm(url) {
            var formDiv = $('<div/>'); // Função que explode o PopUp de cadastro de funcionário 
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);
                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Preencha os dados do funcionário',
                        Urleight: 700,
                        width: 700,
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }
                    });
                });
        }
        function SubmitForm(form) { // Função que valida se o formulário da view AddOrEdit está válido e realiza uma requisição POST pra envio dos dados
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })

                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) { // Essa função deleta o registro a partir do id selecionado
            if (confirm('Tem certe que quer deletar o registro?')) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "Funcionario")/' + id,
                    success: function (data) {
                        if (data.success) {
                            dataTable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className: "success"
                            })
                        }
                    }
                })
            }
        }
    </script>
}

OngCrud/Views/Home/Inicio.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/stylemenu.css">
</head>

<body>
    <style>
        * {
            padding: 0;
            margin: 0;
            font-family: Arial;
            font-size: 15px;
            list-style: none;
            text-decoration: none;
            /*box-sizing: border-box;*/
        }

        :root {
            --cor-fundo: rgb(34, 41, 37);
            --cor-hover: rgb(118, 180, 145);
            --cor-primaria: rgb(231, 241, 236);
        }

        .header {
            width: 2000px;
            height: 120px;
            margin: auto;
            background: linear-gradient(120deg, #48e950, #00c2c8);
        }

        .dp-menu ul {
            list-style-type: none;
            padding: 0;
            margin: 0;
            margin-top: 0;
        }

        .dp-menu ul {
            background-color: var(--cor-fundo);
            margin: 0;
            padding: 0;
            flex-basis: auto;
        }

            .dp-menu ul li {
                display: inline;
                position: relative;
            }

                .dp-menu ul li a {
                    color: var(--cor-primaria);
                    font-family: Arial;
                    display: inline-block;
                    transition: background .3s;
                    width: 100px;
                    padding: 14px 20px;
                    align-items: center;
                    flex-direction: column;
                    text-decoration: none;
                }

                    .dp-menu ul li a:hover {
                        background-color: var(--cor-hover);
                    }

            /*sub menu*/
            .dp-menu ul ul {
                display: none;
                left: 0;
                position: absolute;
            }

            .dp-menu ul li:hover ul {
                display: block;
            }

            .dp-menu ul ul {
                width: 100px
            }

                .dp-menu ul ul li a {
                    display: block;
                }

            .logo {
            float: left;
            color: white;
            font-size: 27px;
            font-weight: 600;
            line-height: 120px;
            padding-left: 20px;
        }

    </style>
    <div class="header logo">ONG Jovens Ambientalistas 2021</div>
    <nav class="dp-menu">
        <ul>
            <li>
                <a href="#" style="align-items: center;">Aluno</a>
                <ul class="teste">
                    <li><a href="@Url.Action("Curso", "Aluno")">Cursos</a></li>
                    <li><a href="#">Grade Curricular</a></li>
                    <li><a href="#">Notas</a></li>
                    <li><a href="#" style="color: red;">Tarefas</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Professor</a>
                <ul>
                    <li><a href="#">Agenda</a></li>
                    <li><a href="#">Lançar notas</a></li>
                    <li><a href="#">Lançar presença</a></li>
                    <li><a href="#">Lançar Atividades</a></li>
                    <li><a href="#">Notícias</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Financeiro</a>
                <ul>
                    <li><a href="#">Estoque</a></li>
                    <li><a href="#">Lucro</a></li>
                    <li><a href="#">Produtos</a></li>
                    <li><a href="#">Relatórios</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Secretaria</a>
                <ul>
                    <li><a href="#">Cadastrar Curso</a></li>
                    <li><a href="#">Cadastrar Disciplina</a></li>
                    <li><a href="#">Cadastrar Turma</a></li>
                    <li><a href="#">Cadastrar Usuário</a></li>
                    <li><a href="@Url.Action("Index", "Funcionario")">Cadastrar Funcionário</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Funcionário</a>
                <ul>
                    <li><a href="#">Consulta Ponto</a></li>
                    <li><a href="#">Holerite</a></li>
                    <li><a href="#">Atividade</a></li>
                </ul>
            </li>
            <li>
                <a href="#">Cadastro</a>
                <ul>
                    <li><a href="#">Meu Cadastro</a></li>
                    <li><a href="#">Alterar Senha</a></li>
                </ul>
            </li>

        </ul>
    </nav>
</body>
</html>

OngCrud/Views/Professor/Agenda.cshtml
<h2>Agenda</h2>
<table id="FuncTable" class="ui celled table" style="width:100%">
    <thead>
        <tr>
            <th>Segunda</th>
            <th>Terça-Feira</th>
            <th>Quarta-Feira</th>
            <th>Quinta-Feira</th>
            <th>Sexta-Feira</th>
            <th>Sábado</th>
            <th>Domingo</th>
        </tr>
    </thead>
</table>
<a class="btn btn-default" style="align-items:center" href="@Url.Action("Inicio", "Home")"><i class="fas fa-arrow-left"></i> Voltar</a>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/1.10.24/css/dataTables.semanticui.min.css" rel="stylesheet" />


@section scripts{
    <script src="//cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.bootstrap.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.24/js/dataTables.semanticui.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.1/semantic.min.js"></script>
    <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" data-auto-replace-svg="nest"></script>
    <script>
        var Popup, dataTable;
        $(document).ready(function () { // Função ajax pra popular a tabela quando a página abrir
            dataTable = $("#FuncTable").DataTable({
                "ajax": {
                    "url": "/Aluno/CursoDados",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "NomeCurso" },
                    { "data": "Professor" },
                    { "data": "Status" },
                    {
                        "data": "CursoId",
                        "visible": false,
                        "orderable": false,
                        "searchable": false,
                        "width": "165px"
                    }
                ],
                "language": {
                    "emptyTable": "Não há dados disponíveis."
                }
            });
        });
    </script>
}

OngCrud/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title ONG J.A</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />
</head>
<body>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>ONG Jovens Ambientalistas</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.12.4.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>